### ISSUE TITLE
Failed to resolve: tablayout2-1.0.0

### ISSUE THREAD

**Issue by yonglf** [fanmingyi/FlycoTabLayout2#1]

**Comment by fanmingyi** [comment]
Add `Jcenter` repository  to your root `build.gradle`,for example:
```goovy
allprojects {
    repositories {
        jcenter()
     }
}
```

**Comment by yonglf** [comment]
@fanmingyi 
![image](https://user-images.githubusercontent.com/26603973/105467584-db789d80-5cd0-11eb-9f3d-767eaa73a457.png)

**Comment by yonglf** [comment]
一样的  失败

**Comment by fanmingyi** [comment]
I'm sure artifact has been published.

It's also normal for my friends to declare  dependent. 

Please browse the following URL：
 https://bintray.com/bintray/jcenter?filterByPkgName=FlycoTabLayout2


 Check your network is normal。(翻墙)
