### ISSUE TITLE
支持了ViewPager2 但是tab 不能动态增加

### ISSUE THREAD

**Issue by LinTaoAndroid** [fanmingyi/FlycoTabLayout2#3]

**Comment by fanmingyi** [comment]
SlidingTabLayout2 于SlidingTabLayout实现都是一样。少了哪个函数吗？动态添加在多数情况都是不需要的。这可以也支持动态添加，只需要更改适配器和重新初始化即可

**Comment by LinTaoAndroid** [comment]
嗯,谢谢了, 拿到server端返回数据重新初始化tablayout就行了
